Add files via upload
cleaned up some things

diff --git a/wipri b/wipri
--- a/wipri
+++ b/wipri
@@ -189,7 +189,7 @@ function hostn {
 	array[10]="phone"
 	groupnum=$[ $RANDOM % 11 ]
 	hostbase=${array[$groupnum]}
-	hostnamectl set-hostname $hostbase
+	hostnamectl set-hostname $hostbase || hostname $hostbase
 ### Below commented out for now - reverted back to more generic as this was 2yr ago (better blending in)
 #	if [ $hostbase == "localhost" ]; then
 #       	hostnamectl set-hostname localhost
@@ -204,8 +204,8 @@ function hostn {
 #        	/bin/echo -e "$BLUE Hostname (logged by router/network) is now $ENDCOLOR$RED$randhostname $ENDCOLOR"
 #	fi
 
-	dhclient -r $netdev
-	dhclient $netdev
+	dhclient -r $netdev || echo -e "${RED}dhclient not found - OK we can still change things${ENDCOLOR}"
+	dhclient $netdev || echo -e "${RED}dhclient not found - OK we can still make due without it${ENDCOLOR}"
 }
 
 # MAC randomization/setting
@@ -214,7 +214,7 @@ function macrand {
 	beg=$(shuf -n 1 $oui_file)      # $oui_file contains important info to generate valid random macs: ma>
 	end=$( for i in {1..6} ; do echo -n ${hexchar:$(( $RANDOM % 16 )):1} ; done | sed -e 's/\(..\)/:\1/g' )
 	mac=$beg$end
-	/bin/echo -e "$BLUE Changing MAC to:${ENDCOLOR} $RED$mac$ENDCOLOR"
+	/bin/echo -e "${BLUE}Changing MAC to:${ENDCOLOR} $RED$mac$ENDCOLOR"
 	ip link set dev $netdev down;ip link set dev $netdev address $mac;ip link set dev $netdev up;
     	echo ""
 }
@@ -226,7 +226,7 @@ function phmacrand {
 	beg=$(shuf -n 1 $phoui_file)      # $phoui_file contains important info to generate valid random phone macs
     	end=$( for i in {1..6} ; do echo -n ${hexchar:$(( $RANDOM % 16 )):1} ; done | sed -e 's/\(..\)/:\1/g' )
     	mac=$beg$end
-    	/bin/echo -e "$BLUE Changing MAC to:${ENDCOLOR} $RED$mac$ENDCOLOR"
+    	/bin/echo -e "${BLUE}Changing MAC to:${ENDCOLOR} ${RED}$mac${ENDCOLOR}"
     	ip link set dev $netdev down;ip link set dev $netdev address $mac;ip link set dev $netdev up;
     	echo ""
 }
@@ -235,11 +235,11 @@ function phmacrand {
 function signaljumper() {
 	hightx=30                      # WARNING: stay w/in bounds of tx regulations for your country
 	lowtx=3                        # lower number for txpower variations
-	echo -e "$BLUE signal variation (experimental): $RED ON $ENDCOLOR"
+	echo -e "${BLUE}signal variation (experimental):${ENDCOLOR} ${RED}ON$ENDCOLOR"
 	randtx=$((RANDOM%$hightx+$lowtx))
 	sleep 1
 	iwconfig $netdev txpower $randtx
-	echo -e "$BLUE setting $netdev tx power: $RED $randtx"
+	echo -e "${BLUE} setting $netdev tx power:${ENDCOLOR} ${RED}$randtx${ENDCOLOR}"
 }
 
 # prevent static flag leaks
@@ -350,7 +350,7 @@ while getopts ":d:wapPrm:ihRsAH" arg; do
 	# Device setting [-d devicename] [REQUIRED: with all MAC related functions]
      d)
 	  netdev=${OPTARG}
-	  echo -e "device is $RED $netdev $ENDCOLOR" 
+	  echo -e "device is ${RED}$netdev${ENDCOLOR}" 
 	  export netdev				  	  
 	  ;;
 
@@ -365,11 +365,11 @@ while getopts ":d:wapPrm:ihRsAH" arg; do
 	# coordinating all 3 options to happen simultaneously scheduled at
     # continually changing randomized time periods
      a)
-	echo -e "$BLUE WiPri Anonymous mode starting... $ENDCOLOR"
-	echo -e "$BLUE [Coordinated MAC/Hostnames/Txpower] - at continually changing times/addresses] $ENDCOLOR"
-	echo -e "$BLUE [randomized MAC addresses + hostnames + signal strength in unison help confuse trackers]"
+	echo -e "${BLUE}WiPri Anonymous mode starting...${ENDCOLOR}"
+	echo -e "${BLUE}[Coordinated MAC/Hostnames/Txpower] - at continually changing times/addresses]${ENDCOLOR}"
+	echo -e "${BLUE}[randomized MAC addresses + hostnames + signal strength in unison help confuse trackers]${ENDCOLOR}"
 	echo ""
-	/bin/echo -e "$BLUE ghosting MAC/device name $ENDCOLOR: $BLUE random times at random addresses '(MAC address in privacy mode)'"
+	/bin/echo -e "${BLUE}ghosting MAC/device name ${ENDCOLOR}: ${BLUE}random times at random addresses '(MAC address in privacy mode)'${ENDCOLOR}"
 
        while :
        do
@@ -379,7 +379,7 @@ while getopts ":d:wapPrm:ihRsAH" arg; do
            	macrand ; hostn; signaljumper 
 		# maccheck - to be worked out later
        		echo ""
-        	/bin/echo -e "$BLUE next changes [New Device]: random times/MAC addresses/signal in: $RED $rando $ENDCOLOR$BLUE sec $ENDCOLOR"
+        	/bin/echo -e "${BLUE}next changes [New Device]: random times/MAC addresses/signal in: ${RED}$rando${ENDCOLOR} ${BLUE}sec${ENDCOLOR}"
            	sleep $rando
 		# killall -9 maccheck
        done
@@ -399,9 +399,9 @@ while getopts ":d:wapPrm:ihRsAH" arg; do
        		rando=$((RANDOM%$hightime+$lowtime))
            	phmacrand
 		# maccheck TBC
-           	echo -e "$RED randomizing MAC addresses at continually changing times/iPhone / Android addresses $ENDCOLOR"
-           	/bin/echo -e "$BLUE Changing MAC to: $RED$mac$ENDCOLOR"
-           	/bin/echo -e "$BLUE next changes: random times, random addresses in: $RED $rando$BLUE sec$ENDCOLOR"
+           	echo -e "${RED} randomizing MAC addresses at continually changing times/iPhone / Android addresses ${ENDCOLOR}"
+           	/bin/echo -e "${BLUE} Changing MAC to: ${RED}$mac${ENDCOLOR}"
+           	/bin/echo -e "${BLUE} next changes: random times, random addresses in: ${RED} $rando${BLUE} sec${ENDCOLOR}"
            	sleep $rando
 		# killall -9 maccheck
        done
@@ -409,15 +409,15 @@ while getopts ":d:wapPrm:ihRsAH" arg; do
 
 	# Continually randomizing MAC address mode [changing times/addresses- all brands]
      r)
-	echo -e "$RED randomizing MAC address at continually changing times/addresses $ENDCOLOR"
+	echo -e "${RED}randomizing MAC address at continually changing times/addresses ${ENDCOLOR}"
 
        	while :
 	do
 		rando=$((RANDOM%$hightime+$lowtime))
 		macrand
 		# maccheck # TBC
-		/bin/echo -e "$BLUE Changing MAC to: $RED$mac$ENDCOLOR"
-           	/bin/echo -e "$BLUE next changes: random times, random addresses in: $RED $rando$BLUE sec$ENDCOLOR"
+		#/bin/echo -e "${BLUE} Changing MAC to: ${RED}$mac${ENDCOLOR}"
+           	/bin/echo -e "${BLUE} next changes: random times, random addresses in:${ENDCOLOR} ${RED} $rando${ENDCOLOR}${BLUE} sec${ENDCOLOR}"
 	       	sleep $rando
 		# killall -9 maccheck
 	done
@@ -426,7 +426,7 @@ while getopts ":d:wapPrm:ihRsAH" arg; do
 
 	# Set your own static MAC choice with -m
      m)
-	echo -e "$BLUE setting static: $RED ${OPTARG} $ENDCOLOR"
+	echo -e "${BLUE} setting static: ${RED} ${OPTARG} ${ENDCOLOR}"
 	mac=${OPTARG}
 	ip link set dev $netdev down;ip link set dev $netdev address $mac;ip link set dev $netdev up;
 	maccheck 
@@ -435,7 +435,7 @@ while getopts ":d:wapPrm:ihRsAH" arg; do
 
 	# New MAC identity option [-i] single randomized MAC address to be held as long as wipri running
      i)
-	echo -e "$BLUE new static random valid MAC identity ($RED HELD: $BLUE checked/retained to prevent leaks) $ENDCOLOR"
+	echo -e "${BLUE}new static random valid MAC identity${ENDCOLOR} ${RED}(HELD:${ENDCOLOR} ${BLUE}checked/retained to prevent leaks)${ENDCOLOR}"
 	macrand
 	maccheck 
 	;;
@@ -449,7 +449,7 @@ while getopts ":d:wapPrm:ihRsAH" arg; do
 	# Restore your previous MAC address [must have first used -h to save address]
      R)
 	if [ ! -f /etc/wipri/hostname.saved ]; then
-		echo -e "$RED ERROR! Previously saved hostname does NOT exist!" >> /dev/stderr 
+		echo -e "${RED}ERROR! Previously saved hostname does NOT exist!${ENDCOLOR}" >> /dev/stderr 
 		sleep .5
 		echo ""
 	else
@@ -457,7 +457,7 @@ while getopts ":d:wapPrm:ihRsAH" arg; do
 		hostnamectl set-hostname $ORG_HOSTNAME
 		dhclient -r $netdev
 	       	dhclient $netdev
-		echo -e " $GREEN*$BLUE Hostname restored to $ORG_HOSTNAME\n"
+		echo -e " ${GREEN}*${ENDCOLOR} ${BLUE}Hostname restored to $ORG_HOSTNAME${ENDCOLOR}\n"
 		sleep .5	
 		rm /etc/wipri/hostname.saved
 	fi
@@ -489,7 +489,7 @@ while getopts ":d:wapPrm:ihRsAH" arg; do
         # wipri -d $netdev -i &  	# uncomment this if you don't want to have to run flags for mac
         systemctl restart hostapd
 	echo ' '
-	/bin/echo -e "$BLUE WiFi Network SSID changed to: $RED $randname $ENDCOLOR"
+	/bin/echo -e "${BLUE}WiFi Network SSID changed to:${ENDCOLOR} ${RED}$randname${ENDCOLOR}"
         # Notify remote server of new name change via Netcat [set $ncnotify variable for on/off: default off]
         notify
 
@@ -500,45 +500,45 @@ while getopts ":d:wapPrm:ihRsAH" arg; do
 
 	sleep .75
 	echo ""
-	echo -e "$WHITE WiPri uses whichever flags you choose to use. $ENDCOLOR"
-	echo -e "$RED [Careful not to combine flags that conflict with one another] $ENDCOLOR"
-	echo -e "$WHITE To use for seperate devices, run more than once instance $ENDCOLOR"
-	echo -e "$WHITE [I changed format to make integrating into scripts/programs/boot more efficient] $ENDCOLOR"
+	echo -e "${WHITE}WiPri uses whichever flags you choose to use.${ENDCOLOR}"
+	echo -e "${RED}[Careful not to combine flags that conflict with one another] ${ENDCOLOR}"
+	echo -e "${WHITE}To use for seperate devices, run more than once instance${ENDCOLOR}"
+	echo -e "${WHITE}[I changed format to make integrating into scripts/programs/boot more efficient]${ENDCOLOR}"
 	echo "" && sleep .2
-	echo -e "$WHITE Example #1:$ENDCOLOR wipri -d wlan0 -r -h on -s"
-	echo -e "$BLUE [Above] randomize wlan0 at continuously changing times/MAC addresses; randomize hostname; location randomization $ENDCOLOR"
-	echo -e "$BLUE -r mode is ideal for fluid situations- when travelling it can help protect identity; $ENDCOLOR"
-	echo -e "$WHITE Example #2:$ENDCOLOR wipri -d wlan1 -m 00:00:00:00:00:00 -h off -s off"
-	echo -e "$BLUE [Above] sets wlan1 MAC of your choice (static); hostname change [off]; signal changes [off]"
+	echo -e "${WHITE} Example #1:${ENDCOLOR}wipri -d wlan0 -r -h on -s"
+	echo -e "${BLUE}[Above] randomize wlan0 at continuously changing times/MAC addresses; randomize hostname; location randomization ${ENDCOLOR}"
+	echo -e "${BLUE} -r mode is ideal for fluid situations- when travelling it can help protect identity;${ENDCOLOR}"
+	echo -e "${WHITE}Example #2:${ENDCOLOR} wipri -d wlan1 -m 00:00:00:00:00:00 -h off -s off"
+	echo -e "${BLUE}[Above] sets wlan1 MAC of your choice (static); hostname change [off]; signal changes [off]${ENDCOLOR}"
        	echo "" && sleep .2
-       	echo -e "$WHITE Example #3:$ENDCOLOR wipri -d wlan0 -i -h -s"
-       	echo -e "$BLUE [Above] sets wlan0 static random MAC identity; hostname changes; signal changes [on]"
+       	echo -e "${WHITE}Example #3:${ENDCOLOR} wipri -d wlan0 -i -h -s"
+       	echo -e "${BLUE}[Above] sets wlan0 static random MAC identity; hostname changes; signal changes [on]${ENDCOLOR}"
 	echo "" && sleep .2
-	echo -e "$WHITE Example #4:$ENDCOLOR wipri -d wlan1mon -M"
-	echo -e "$BLUE [Above] sets wlan1mon to new random MAC identity (static/single MAC) hostname/signal changes both [OFF]"
+	echo -e "${WHITE}Example #4:${ENDCOLOR} wipri -d wlan1mon -M"
+	echo -e "${BLUE}[Above] sets wlan1mon to new random MAC identity (static/single MAC) hostname/signal changes both [OFF]${ENDCOLOR}"
 	echo "" && sleep .2
-	echo -e "$WHITE Example #5:$ENDCOLOR wipri -R"
-	echo -e "$BLUE [Above] sets/reverts back to original hostname: $RED NOTE: MUST HAVE USED -h PREVIOUSLY $ENDCOLOR"
+	echo -e "${WHITE}Example #5:${ENDCOLOR} wipri -R"
+	echo -e "${BLUE}[Above] sets/reverts back to original hostname: ${RED}NOTE: MUST HAVE USED -h PREVIOUSLY${ENDCOLOR}"
 	echo "" && sleep .2
-       	echo -e "$WHITE Example #6:$ENDCOLOR wipri -d wlan0 -a"
-       	echo -e "$BLUE [Above] continuously changing: randomized [wlan0] MAC addresses + hostnames $ENDCOLOR"
-	echo -e "$BLUE + signal randomization, each changing at the same time, continually; $ENDCOLOR"
+       	echo -e "${WHITE}Example #6:${ENDCOLOR} wipri -d wlan0 -a"
+       	echo -e "${BLUE}Above] continuously changing: randomized [wlan0] MAC addresses + hostnames ${ENDCOLOR}"
+	echo -e "${BLUE}+ signal randomization, each changing at the same time, continually; ${ENDCOLOR}"
 	echo "" && sleep .2
-        echo -e "$WHITE Example #7:${ENDCOLOR} wipri -d wlan0 -P -s"
-        echo -e "$BLUE [Above] sets wlan0 continuously changing times/smartphone MAC identities; -s adds txpower changes [on]"
+        echo -e "${WHITE}Example #7:${ENDCOLOR} wipri -d wlan0 -P -s"
+        echo -e "${BLUE}[Above] sets wlan0 continuously changing times/smartphone MAC identities; -s adds txpower changes [on]${ENDCOLOR}"
         echo "" && sleep .2
-        echo -e "$WHITE Example #8:${ENDCOLOR} wipri -d wlan0 -p"
-        echo -e "$BLUE [Above] sets wlan0 to single random smartphone MAC identity"
+        echo -e "${WHITE}Example #8:${ENDCOLOR} wipri -d wlan0 -p"
+        echo -e "${BLUE}[Above] sets wlan0 to single random smartphone MAC identity"
         echo "" && sleep .2
-        echo -e "$WHITE Example #9:${ENDCOLOR} wipri -d wlan0 -A"
-        echo -e "$BLUE [Above] sets wlan0 hostapd WiFi Access Point to randomized SSID (Network Name)${ENDCOLOR}"
+        echo -e "${WHITE}Example #9:${ENDCOLOR} wipri -d wlan0 -A"
+        echo -e "${BLUE}[Above] sets wlan0 hostapd WiFi Access Point to randomized SSID (Network Name)${ENDCOLOR}"
 	echo "" && sleep .2
 	echo -e "${WHITE} Example #10:${ENDCOLOR} wipri -d wlan0 -w -p"
 	echo -e "${BLUE} [Above] -w sets wlan0 dev to turn off wifi radio when not in range with saved networks preventing SSID probe leak: -p: static Apple/Android${ENDCOLOR}"
 	echo "" && sleep .2
 
 
-	echo -e "$WHITE For more details:$ENDCOLOR $RED README.md$ENDCOLOR"
+	echo -e "${WHITE} For more details:${ENDCOLOR} ${RED}README.md${ENDCOLOR}"
 	;;
     esac
 done
